version: '3'
services:
    #cli
    php56-cli:
        image: php5.6:2.0
        volumes:
            - "$PWD:/var/www/html"
            - "~/data/github/docker-conf/src/config/nginx/server/cron.conf:/usr/local/nginx/conf/cron.conf"
            - "~/data1:/data1"
    php72-cli:
        image: php7.2:2.0
        volumes:
            - "$PWD:/var/www/html"
            - "~/data/github/docker-conf/src/config/nginx/server/cron.conf:/usr/local/nginx/conf/cron.conf"
            - "~/data1:/data1"