version: '3'
services:
  my_redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - "../../data/redis/data:/data"
    command: redis-server --appendonly yes
    networks:
      app_net:
        ipv4_address: 172.16.238.11