version: '3'
services:
  my_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - my_fpm56:php56
      - my_fpm72:php72
    volumes:
      - "~/data/www:/data/www"
      - "../../config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "../../config/nginx/conf.d:/etc/nginx/conf.d"
      - "../../config/nginx/server:/etc/nginx/server"
      - "../../var/log/nginx:/var/log/nginx"
    networks:
      app_net:
        ipv4_address: 172.16.238.2
  my_fpm56:
    image: php5.6:2.0
    volumes:
      - "../../config/php5.6/php.ini:/usr/local/etc/php/php.ini:ro"
      - "~/data/www:/data/www"
      - "~/data1:/data1"
    networks:
      default:
      app_net:
        ipv4_address: 172.16.238.3
    extra_hosts:
      - "local.php56.com:172.16.238.2"
  my_fpm72:
    image: php7.2:2.0
    volumes:
      - "../../config/php7.2/php.ini:/usr/local/etc/php/php.ini:ro"
      - "~/data/www:/data/www"
      - "~/data1:/data1"
    networks:
      default:
      app_net:
        ipv4_address: 172.16.238.4
    extra_hosts:
      - "local.php72.com:172.16.238.2"